# Generated by Django 4.1.5 on 2023-01-27 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("secondapp", "0002_iprod_delete_cart"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="iprod",
            table="lprod",
        ),
    ]
