# Generated by Django 4.1.5 on 2023-01-26 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "cart_no",
                    models.CharField(max_length=13, primary_key=True, serialize=False),
                ),
                ("cat_prod", models.CharField(max_length=30)),
                ("cat_member", models.CharField(max_length=15)),
                ("cat_qty", models.IntegerField(max_length=10)),
            ],
            options={
                "db_table": "cart",
                "managed": False,
            },
        ),
    ]
